language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.3
install:
    - pip install
    - pip install zope.catalog[test]
script:
    - python setup.py test -q
notifications:
    email: false
