language: python
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
#   PyPy3 blocked on a compatible release of 'zodbpickle'
#   - TOXENV=pypy3
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
